// OWNER - HEET
// PURPOSE - Shared styles for the mobile crowd alert app.

import { StyleSheet } from 'react-native';

import { palette } from '../theme';

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: palette.background,
  },
  header: {
    backgroundColor: palette.surfaceDark,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  headerText: {
    flex: 1,
  },
  appName: {
    color: '#AEB8C2',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  place: {
    color: '#FFFFFF',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
    marginTop: 3,
  },
  path: {
    color: '#D5DCE3',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 96,
    gap: 14,
  },
  card: {
    backgroundColor: palette.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  incidentCard: {
    borderLeftWidth: 5,
    borderLeftColor: palette.danger,
    gap: 14,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  updatedAt: {
    color: palette.textSubtle,
    fontSize: 12,
    lineHeight: 16,
  },
  incidentTitle: {
    color: palette.text,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '800',
  },
  incidentLocation: {
    color: palette.textMuted,
    fontSize: 15,
    lineHeight: 21,
  },
  timerBox: {
    backgroundColor: palette.dangerSoft,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F4C9C9',
    padding: 14,
  },
  timerLabel: {
    color: palette.danger,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  timerValue: {
    color: palette.danger,
    fontSize: 42,
    lineHeight: 48,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  reasonList: {
    gap: 8,
  },
  reasonRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  reasonDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: palette.danger,
    marginTop: 7,
  },
  reasonText: {
    flex: 1,
    color: palette.text,
    fontSize: 15,
    lineHeight: 22,
  },
  primaryButton: {
    backgroundColor: palette.primary,
    borderRadius: 8,
    padding: 15,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
  },
  primaryButtonMeta: {
    color: '#DDE9FF',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  metricStrip: {
    backgroundColor: palette.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  stripItem: {
    flex: 1,
    padding: 12,
    borderRightWidth: 1,
    borderRightColor: palette.border,
  },
  smallDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    marginBottom: 6,
  },
  stripLabel: {
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  stripValue: {
    color: palette.text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    marginTop: 2,
  },
  stripHelper: {
    color: palette.textSubtle,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  zoneList: {
    marginTop: 12,
    gap: 12,
  },
  zoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  zoneLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  statusBar: {
    width: 4,
    height: 36,
    borderRadius: 2,
  },
  zoneName: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '700',
  },
  zoneArea: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  zoneDensity: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  actionCard: {
    borderLeftWidth: 5,
    borderLeftColor: palette.inactive,
  },
  primaryActionCard: {
    borderColor: palette.primary,
    borderLeftWidth: 5,
    borderLeftColor: palette.primary,
  },
  actionTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  actionCopy: {
    flex: 1,
  },
  actionOwner: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  actionTitle: {
    color: palette.text,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '800',
    marginTop: 3,
  },
  actionTarget: {
    color: palette.primary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    marginTop: 2,
  },
  actionNote: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  primaryTag: {
    color: palette.primary,
    backgroundColor: palette.primarySoft,
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  dispatchButton: {
    backgroundColor: palette.primary,
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  dispatchText: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '800',
  },
  secondaryButton: {
    backgroundColor: palette.surfaceMuted,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  secondaryText: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '700',
  },
  metricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    gap: 12,
  },
  metricLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metricRowLabel: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  metricRowValue: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '800',
  },
  warningLabel: {
    color: palette.warning,
    backgroundColor: palette.warningSoft,
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  chart: {
    height: 170,
    backgroundColor: '#FBFCFE',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    marginTop: 14,
    padding: 12,
    position: 'relative',
  },
  thresholdLine: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: '47%',
    height: 1,
    backgroundColor: palette.warning,
  },
  thresholdText: {
    position: 'absolute',
    right: 14,
    bottom: '48%',
    color: palette.warning,
    fontSize: 11,
    lineHeight: 14,
    backgroundColor: '#FBFCFE',
    paddingHorizontal: 4,
  },
  chartPoint: {
    position: 'absolute',
    width: 11,
    height: 11,
    borderRadius: 6,
    marginLeft: -5,
  },
  chartLabels: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  chartLabel: {
    color: palette.textSubtle,
    fontSize: 11,
    lineHeight: 14,
  },
  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 72,
    backgroundColor: palette.surface,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingTop: 8,
    gap: 8,
  },
  navItem: {
    flex: 1,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navItemActive: {
    backgroundColor: palette.primarySoft,
  },
  navLabel: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  navLabelActive: {
    color: palette.primary,
  },
});
