// OWNER - HEET
// PURPOSE - Shared styles for the mobile crowd alert app.

import { StyleSheet, Animated } from 'react-native';

import { palette } from '../theme';

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: palette.background,
  },
  header: {
    backgroundColor: palette.surfaceDark,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  headerText: {
    flex: 1,
  },
  appName: {
    color: '#AEB8C2',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  place: {
    color: '#FFFFFF',
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
    marginTop: 3,
  },
  path: {
    color: '#D5DCE3',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 2,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 96,
    gap: 16,
  },
  card: {
    backgroundColor: palette.surface,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  incidentCard: {
    borderLeftWidth: 5,
    borderLeftColor: palette.danger,
    gap: 14,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  updatedAt: {
    color: palette.textSubtle,
    fontSize: 12,
    lineHeight: 16,
  },
  incidentTitle: {
    color: palette.text,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '800',
  },
  incidentLocation: {
    color: palette.textMuted,
    fontSize: 15,
    lineHeight: 21,
  },
  timerBox: {
    backgroundColor: palette.dangerSoft,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.dangerSoft,
    padding: 14,
  },
  timerLabel: {
    color: palette.danger,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  timerValue: {
    color: palette.danger,
    fontSize: 42,
    lineHeight: 48,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  reasonList: {
    gap: 8,
  },
  reasonRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  reasonDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: palette.danger,
    marginTop: 7,
  },
  reasonText: {
    flex: 1,
    color: palette.text,
    fontSize: 15,
    lineHeight: 22,
  },

  metricStrip: {
    backgroundColor: palette.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  stripItem: {
    flex: 1,
    padding: 12,
    borderRightWidth: 1,
    borderRightColor: palette.border,
  },
  smallDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    marginBottom: 6,
  },
  stripLabel: {
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  stripValue: {
    color: palette.text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    marginTop: 2,
  },
  stripHelper: {
    color: palette.textSubtle,
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  zoneList: {
    marginTop: 12,
    gap: 12,
  },
  zoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  zoneLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  statusBar: {
    width: 4,
    height: 36,
    borderRadius: 2,
  },
  zoneName: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '700',
  },
  zoneArea: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  zoneDensity: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  actionCard: {
    borderLeftWidth: 5,
    borderLeftColor: palette.inactive,
  },
  primaryActionCard: {
    borderColor: palette.primary,
    borderLeftWidth: 5,
    borderLeftColor: palette.primary,
  },
  actionTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  actionCopy: {
    flex: 1,
  },
  actionOwner: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  actionTitle: {
    color: palette.text,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '800',
    marginTop: 3,
  },
  actionTarget: {
    color: palette.primary,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    marginTop: 2,
  },
  actionNote: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  primaryTag: {
    color: palette.primary,
    backgroundColor: palette.primarySoft,
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },

  metricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    gap: 12,
  },
  metricLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  metricRowLabel: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  metricRowValue: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '800',
  },
  warningLabel: {
    color: palette.warning,
    backgroundColor: palette.warningSoft,
    borderRadius: 999,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },

  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 72,
    backgroundColor: palette.surface,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingTop: 8,
    gap: 8,
  },
  navItem: {
    flex: 1,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navItemActive: {
    backgroundColor: palette.primarySoft,
  },
  navLabel: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
  },
  navLabelActive: {
    color: palette.primary,
  },
  navIcon: {
    fontSize: 20,
    marginBottom: 2,
  },
  headerBadge: {
    position: 'absolute',
    right: -4,
    top: -4,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.danger,
  },
  headerBadgePulsing: {
    position: 'absolute',
    right: -4,
    top: -4,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.danger,
  },
  alertPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 8,
  },
  alertPillIcon: {
    fontSize: 18,
  },
  alertPillText: {
    fontSize: 15,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  countdownBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    gap: 12,
  },
  countdownIcon: {
    fontSize: 32,
  },
  countdownValue: {
    fontSize: 48,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  countdownLabel: {
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 12,
  },
  metricCardIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricCardContent: {
    flex: 1,
  },
  metricCardLabel: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 2,
  },
  metricCardValue: {
    fontSize: 22,
    fontWeight: '900',
  },
  metricCardTrend: {
    fontSize: 14,
    fontWeight: '800',
    marginLeft: 4,
  },
  actionCard: {
    backgroundColor: palette.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    marginBottom: 12,
  },
  primaryActionCard: {
    borderWidth: 2,
    borderColor: palette.primary,
  },
  actionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  actionCardIcon: {
    fontSize: 18,
  },
  actionCardTitle: {
    fontSize: 16,
    fontWeight: '800',
    flex: 1,
  },
  actionCardTag: {
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    textTransform: 'uppercase',
  },
  actionCardMeta: {
    fontSize: 13,
    fontWeight: '600',
    marginTop: 4,
  },
  actionCardDesc: {
    fontSize: 14,
    marginTop: 8,
    lineHeight: 20,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 10,
    gap: 10,
  },
  primaryButtonIcon: {
    fontSize: 20,
  },
  primaryButtonLabel: {
    fontSize: 16,
    fontWeight: '800',
  },
  primaryButtonPressed: {
    opacity: 0.7,
  },
  primaryButtonCompleted: {
    backgroundColor: palette.safe,
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 8,
  },
  secondaryButtonIcon: {
    fontSize: 16,
  },
  reasonItemNew: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 6,
    gap: 10,
  },
  reasonIcon: {
    fontSize: 14,
    marginTop: 3,
  },
  reasonContent: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 6,
  },
  chipIcon: {
    fontSize: 12,
  },
  chipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceMuted,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: palette.text,
  },
});
